### ISSUE TITLE
Episódio VI

### ISSUE THREAD

**Issue by erickmendonca** [GDGAracaju/gdg-open-bar#15]
# Return of The Jedi

Está na hora de começar a temporada 2016 do GDG Open Bar.

**Comment by eduardoborges** [comment]
Polymer 1.0 <3

**Comment by erickmendonca** [comment]
Acho muito massa. Ta a fim de falar sobre? Porque eu mesmo não vi muita coisa do polymer, admito. :)

**Comment by erickmendonca** [comment]
Acho muito massa. Ta a fim de falar sobre? Porque eu mesmo não vi muita coisa do polymer, admito. :)

**Comment by eduardoborges** [comment]
Pode ser ;D
Mostrar pra que serve mesmo né. Tem gente achando que é framework. Uehwhshs

**Comment by haroldofurtado** [comment]
Vai ser ele mesmo?

**Comment by erickmendonca** [comment]
Ainda tá aberto a sugestões!

**Comment by raphaelpanta** [comment]
Se tiver alguém manjando bem de polymer, gostaria de ver, tenho bastante curiosidade em saber se vale a pena usar.

**Comment by raphaelpanta** [comment]
Acho que poderíamos fazer um tema mais geral, sobre essas tecnologias que são utilizadas no cliente. Tem bastante coisa nessa área, podíamos arranjar alguém para falar de EmberJs, Outro para falar do ReactJs, um do polymer. Seria bastante proveitoso!

**Comment by erickmendonca** [comment]
Eu acho que conteúdo estritamente técnico não é bacana para o Open Bar, melhor um BarCode ou Hands-on :)

**Comment by raphaelpanta** [comment]
Entendo!
Vou guardar esses temas e torcer para arranjar palestrantes para um hands-on ou barcode com essas tecnologias. :)

**Comment by eduardoborges** [comment]
Confesso que estou sem ideias. :/

**Comment by erickmendonca** [comment]
Fechando issue por inativade.
